package com.xiaogua.hudtips.client.trigger.dismiss;

import com.xiaogua.hudtips.HUDTips;
import com.xiaogua.hudtips.client.config.HintRule;
import com.xiaogua.hudtips.client.config.HudConfig;

import java.util.HashSet;
import java.util.Map;
import java.util.Set;

/**
 * dismissOn 条件的解析结果 —— 不可变数据类。
 * Parsed result of dismissOn conditions — immutable data class.
 *
 * <p>由 {@link #parse(HintRule, Map)} 工厂方法从
 * {@link HintRule#dismissOn} 列表解析生成，
 * 绑定到 {@link com.xiaogua.hudtips.client.trigger.ActiveHint} 实例上。</p>
 * <p>Generated by the {@link #parse(HintRule, Map)} factory method from
 * the {@link HintRule#dismissOn} list, and bound to
 * {@link com.xiaogua.hudtips.client.trigger.ActiveHint} instances.</p>
 *
 * <h2>三种关闭机制 / Three Dismiss Mechanisms</h2>
 * <table border="1">
 *   <tr><th>语法 / Syntax</th><th>解析为 / Parsed As</th><th>判断方式 / Check Method</th><th>计时基准 / Timing Basis</th></tr>
 *   <tr><td>{@code "time:5000"}</td><td>{@link #timeMs} = 5000</td>
 *       <td>{@code System.currentTimeMillis() - start >= timeMs}</td>
 *       <td>真实时间（不受 TPS 影响） / Real time (unaffected by TPS)</td></tr>
 *   <tr><td>{@code "tick:100"}</td><td>{@link #tickCount} = 100</td>
 *       <td>{@code tickDismissCount >= tickCount}</td>
 *       <td>游戏刻（受 TPS 影响） / Game ticks (affected by TPS)</td></tr>
 *   <tr><td>{@code "on_use"} 等 / etc.</td><td>加入 {@link #dismissTriggers} / Added to {@link #dismissTriggers}</td>
 *       <td>对应触发器在 activeTriggers 中出现 / Corresponding trigger appears in activeTriggers</td>
 *       <td>事件驱动 / Event-driven</td></tr>
 * </table>
 *
 * <h2>触发器类型过滤 / Trigger Type Filtering</h2>
 * <p>continuous 型触发器放在 dismissOn 中会被警告，因为它们由条件失效自动处理。
 * 但为了兼容性，它们仍被加入 dismissTriggers ——
 * 在触发判断时被 {@code isContinuousTrigger()} 过滤跳过。</p>
 * <p>Continuous triggers in dismissOn will trigger a warning, since they are auto-handled
 * by condition failure. For compatibility they are still added to dismissTriggers —
 * but filtered out at check time by {@code isContinuousTrigger()}.</p>
 *
 * @see com.xiaogua.hudtips.client.trigger.ActiveHint#isTimeOrTickExpired()
 */
public class DismissConditions {

    // ── dismissOn 语法前缀 / dismissOn syntax prefixes ──

    private static final String PREFIX_TIME = "time:";
    private static final String PREFIX_TICK = "tick:";
    /** 两个前缀长度相同（都是 5）—— 共用此常量截取后面的数值部分 / Both prefixes have the same length (5) — share this constant for extracting the numeric part */
    private static final int PREFIX_LEN = 5;

    // ── 解析结果字段 / Parsed result fields ──

    /** 真实时间关闭阈值（毫秒），0 = 不使用 / Real-time dismiss threshold (ms), 0 = not used */
    public int timeMs = 0;

    /** 游戏刻关闭阈值（ticks），0 = 不使用 / Game tick dismiss threshold (ticks), 0 = not used */
    public int tickCount = 0;

    /** 事件型触发器关闭条件集合 / Set of event trigger dismiss conditions */
    public Set<String> dismissTriggers = new HashSet<>();

    // ============================================================
    //  静态工厂
    //  Static Factory
    // ============================================================

    /**
     * 解析 HintRule 的 dismissOn 列表，生成 DismissConditions。
     * Parse a HintRule's dismissOn list and produce DismissConditions.
     *
     * @param rule                   规则 / Rule
     * @param continuousTriggerCache 触发器类型 → 是否为 continuous 的缓存（由 TriggerManager 维护） / Trigger type → isContinuous cache (maintained by TriggerManager)
     * @return 解析后的消失条件 / Parsed dismiss conditions
     */
    public static DismissConditions parse(HintRule rule, Map<String, Boolean> continuousTriggerCache) {
        DismissConditions conditions = new DismissConditions();

        if (rule.dismissOn == null || rule.dismissOn.isEmpty()) {
            // 未配置 dismissOn：
            //   continuous 型：条件不满足时由 conditionFailed 移除
            //   event 型（普通提示）：默认 5 秒后消失（教程型需显式配置 dismissOn）
            // No dismissOn configured:
            //   continuous type: removed by conditionFailed when condition no longer holds
            //   event type (normal hint): default 5-second timeout (guide type requires explicit dismissOn config)
            if (!rule.isGuideComplete() && hasOnlyEventTriggers(rule, continuousTriggerCache)) {
                conditions.timeMs = 5000;
            }
            return conditions;
        }

        for (String condition : rule.dismissOn) {
            if (condition.startsWith(PREFIX_TIME)) {
                if (conditions.timeMs > 0) {
                    HUDTips.LOGGER.warn("dismissOn 中有多个 time: 条目，只有最后一个生效。" +
                        "规则: {}", rule.text);
                }
                try {
                    conditions.timeMs = Integer.parseInt(condition.substring(PREFIX_LEN));
                } catch (NumberFormatException e) {
                    HUDTips.LOGGER.warn("Invalid time format: {}", condition);
                }
            } else if (condition.startsWith(PREFIX_TICK)) {
                if (conditions.tickCount > 0) {
                    HUDTips.LOGGER.warn("dismissOn 中有多个 tick: 条目，只有最后一个生效。" +
                        "规则: {}", rule.text);
                }
                try {
                    conditions.tickCount = Integer.parseInt(condition.substring(PREFIX_LEN));
                } catch (NumberFormatException e) {
                    HUDTips.LOGGER.warn("Invalid tick format: {}", condition);
                }
            } else {
                if (continuousTriggerCache.getOrDefault(condition, false)) {
                    HUDTips.LOGGER.warn(
                        "dismissOn 中包含 continuous 触发器 \"{}\"，该类型由条件失效自动处理，" +
                        "在 dismissOn 中将被忽略。建议改用 time:/tick: 或移除该条目。规则: {}",
                        condition, rule.text);
                }
                conditions.dismissTriggers.add(condition);
            }
        }
        return conditions;
    }

    /**
     * 判断规则的所有 triggerOn 是否都是 event 型（无 continuous 触发器）。
     * Determine whether all of a rule's triggerOn entries are event-type (no continuous triggers).
     *
     * <p>用于默认超时判断：只有纯 event 型规则才需要默认 5 秒超时。
     * 如果规则中有 continuous 触发器（如 hold_item、on_dimension），
     * 则由 conditionFailed 机制自动处理消失，无需额外超时。</p>
     * <p>Used for default timeout logic: only pure event-type rules need the default 5-second timeout.
     * If a rule has continuous triggers (e.g. hold_item, on_dimension),
     * the conditionFailed mechanism handles dismissal automatically — no extra timeout needed.</p>
     *
     * @param rule                   规则 / Rule
     * @param continuousTriggerCache 触发器类型 → 是否为 continuous 的缓存 / Trigger type → isContinuous cache
     * @return true 如果所有 triggerOn 都是 event 型（且至少有一个） / true if all triggerOn entries are event-type (and there is at least one)
     */
    private static boolean hasOnlyEventTriggers(HintRule rule, Map<String, Boolean> continuousTriggerCache) {
        if (rule.triggerOn == null || rule.triggerOn.isEmpty()) return false;
        for (String triggerType : rule.triggerOn.keySet()) {
            if (continuousTriggerCache.getOrDefault(triggerType, false)) {
                return false;
            }
        }
        return true;
    }
}
